package com.infy.EcommerceApp.controller;

import com.infy.EcommerceApp.service.TokenService;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller class responsible for handling authentication-related endpoints.
 */
@RestController
public class AuthController {

    private final TokenService tokenService;

    /**
     * Constructs a new instance of AuthController with the provided TokenService.
     *
     * @param tokenService The TokenService responsible for token generation.
     */
    public AuthController(TokenService tokenService) {
        this.tokenService = tokenService;
    }

    /**
     * Generates and returns an authentication token based on the provided authentication details.
     *
     * @param authentication The authentication details.
     * @return A token generated by the TokenService.
     */
    @PostMapping("/token")
    public String token(Authentication authentication) {
        String token = tokenService.generateToken(authentication);
        return token;
    }
}

